apiVersion: v1
kind: Secret
metadata:
  name: test
  namespace: openshift-logging
stringData:
  access_key_id: minio
  access_key_secret: minio123
  bucketnames: loki
  endpoint: http://minio.openshift-logging.svc:9000
type: Opaque
