apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: loki-operator-v0.0.1
    app.kubernetes.io/name: loki-operator
    app.kubernetes.io/part-of: loki-operator
    app.kubernetes.io/version: 0.0.1
  name: minio
  namespace: openshift-logging
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app.kubernetes.io/name: loki-operator
    app.kubernetes.io/part-of: loki-operator
  type: ClusterIP
